apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-pvc  # Choose a meaningful name for your PVC
spec:
  accessModes:
    - ReadWriteOnce  # Access mode (single node can read/write)
  resources:
    requests:
      storage: 10Gi  # Storage capacity you need
  storageClassName: longhorn  # Replace with your storage class (if needed)