apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media # Or your desired namespace
spec:
  selector:
	app: radarr
  ports:
	- name: http
	  port: 7878
	  targetPort: 7878
  type: LoadBalancer # Deploy as a standalone IP Addr on network.