apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default # Or your desired namespace
  annotations:
    metalib.universe.tf/loadBalancerIPs: 192.168.0.30
spec:
  selector:
      app: radarr
  ports:
    - name: http
      port: 80
      targetPort: 7878
  type: LoadBalancer # Deploy as a standalone IP Addr on network.
  
  